openapi: 3.0.3
info:
  title: Task Management API for Trello Board
  description: API for managing tasks within a specific Trello board, tailored for integration with GPT Builder in ChatGPT.
  version: 1.0.0
servers:
  - url: http://localhost:5003

paths:
  /tasks:
    post:
      summary: Create a new task
      operationId: createTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskRequest'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'

    get:
      summary: List all tasks
      operationId: listTasks
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskResponse'

  /tasks/{taskId}:
    get:
      summary: Retrieve a specific task
      operationId: getTask
      parameters:
        - name: taskId
          in: path
          required: true
          description: Unique identifier of a task
          schema:
            type: string
      responses:
        '200':
          description: Details of the task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
    
    put:
      summary: Update a specific task
      operationId: updateTask
      parameters:
        - name: taskId
          in: path
          required: true
          description: Unique identifier of a task
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskRequest'
      responses:
        '200':
          description: Task updated successfully
    
    delete:
      summary: Delete a specific task
      operationId: deleteTask
      parameters:
        - name: taskId
          in: path
          required: true
          description: Unique identifier of a task
          schema:
            type: string
      responses:
        '204':
          description: Task deleted successfully

components:
  schemas:
    TaskRequest:
      type: object
      properties:
        title:
          type: string
          description: Title of the task
        description:
          type: string
          description: Detailed description of the task
        status:
          type: string
          description: Current status of the task
      required:
        - title

    TaskResponse:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the task
        title:
          type: string
          description: Title of the task
        description:
          type: string
          description: Detailed description of the task
        status:
          type: string
          description: Current status or list category of the task
      required:
        - id
        - title
        - status
